GENRE=1

genre = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", GENRE,"Jazz"])
genre.children.create(:concept_name => "Big band", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Free jazz", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Lounge music", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Blues", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Latin", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Bebop", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Fusion", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Improvisation", :concept_type_id => GENRE)

genre = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", GENRE,"Popular"])
genre.children.create(:concept_name => "Rock", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Hiphop", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Rap", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Electronica", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Funk", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Popular Te Reo", :concept_type_id => GENRE)

genre = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", GENRE,"Maori Music"])
genre.children.create(:concept_name => "Moteatea", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Waiata", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Kapa haka", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Whare tapere", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Haka", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Karanga", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Kaupapa (protest) music", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Popular cultural", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Popular Te Reo", :concept_type_id => GENRE)

genre = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", GENRE,"20th Century Genres"])
genre.children.create(:concept_name => "Modernism", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Post-modernism", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Avant-garde", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Darmstadt School", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Serialism", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Aleatoric", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Minimalism", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Expressionism", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Neo-romanticism", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Neo-classicism", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Surrealism", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Musique concrète", :concept_type_id => GENRE)

genre = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", GENRE,"19th Century Genres"])
genre.children.create(:concept_name => "Impressionism", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Romanticism", :concept_type_id => GENRE)

genre = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", GENRE,"Pre-19th Century Genres"])
genre.children.create(:concept_name => "Classical", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Baroque", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Renaissance", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Mediaeval", :concept_type_id => GENRE)

genre = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", GENRE,"Nationalism"])
genre.children.create(:concept_name => "Nationalism", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Folk", :concept_type_id => GENRE)

genre = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", GENRE,"Eclecticism"])
genre.children.create(:concept_name => "Eclecticism", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Transcriptions", :concept_type_id => GENRE)

genre = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", GENRE,"Improvisation"])
genre.children.create(:concept_name => "Improvisation", :concept_type_id => GENRE)

genre = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", GENRE,"Sonic Art"])
genre.children.create(:concept_name => "Noise", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Intermedia", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Sound design", :concept_type_id => GENRE)
genre.children.create(:concept_name => "Ars Electronica", :concept_type_id => GENRE)

