THEME=3

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Maori Culture"])
theme.children.create(:concept_name => "Maori - culture", :concept_type_id => THEME)
theme.children.create(:concept_name => "Purakau - legends", :concept_type_id => THEME)
theme.children.create(:concept_name => "Iwi - people", :concept_type_id => THEME)
theme.children.create(:concept_name => "Kaupapa - protest", :concept_type_id => THEME)
theme.children.create(:concept_name => "Moteatea - song poetry", :concept_type_id => THEME)
theme.children.create(:concept_name => "Haka - dance", :concept_type_id => THEME)
theme.children.create(:concept_name => "Waiata - song", :concept_type_id => THEME)
theme.children.create(:concept_name => "Conservation FIXME", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Landscape - other"])
theme.children.create(:concept_name => "Landscape - other", :concept_type_id => THEME)
theme.children.create(:concept_name => "Conservation", :concept_type_id => THEME)
theme.children.create(:concept_name => "Urban", :concept_type_id => THEME)
theme.children.create(:concept_name => "Flora and Fauna - other", :concept_type_id => THEME)
theme.children.create(:concept_name => "Sea and water - other", :concept_type_id => THEME)
theme.children.create(:concept_name => "Travel", :concept_type_id => THEME)
theme.children.create(:concept_name => "Antarctica", :concept_type_id => THEME)
theme.children.create(:concept_name => "Natural History", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Landscape - NZ"])
theme.children.create(:concept_name => "Landscape - NZ", :concept_type_id => THEME)
theme.children.create(:concept_name => "Flora and fauna - NZ", :concept_type_id => THEME)
theme.children.create(:concept_name => "Birds - NZ", :concept_type_id => THEME)
theme.children.create(:concept_name => "Sea and water - NZ", :concept_type_id => THEME)
theme.children.create(:concept_name => "Urban - NZ", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Natural History"])
theme.children.create(:concept_name => "Flora and Fauna - other", :concept_type_id => THEME)
theme.children.create(:concept_name => "Natural History", :concept_type_id => THEME)
theme.children.create(:concept_name => "Flora and fauna - NZ", :concept_type_id => THEME)
theme.children.create(:concept_name => "Birds - NZ", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Culture - NZ"])
theme.children.create(:concept_name => "Culture - NZ", :concept_type_id => THEME)
theme.children.create(:concept_name => "History - NZ", :concept_type_id => THEME)
theme.children.create(:concept_name => "People - NZ", :concept_type_id => THEME)
theme.children.create(:concept_name => "Art and literature - NZ", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Culture - South Pacific"])
theme.children.create(:concept_name => "South Pacific - history and culture", :concept_type_id => THEME)
theme.children.create(:concept_name => "Samoa - history and culture", :concept_type_id => THEME)
theme.children.create(:concept_name => "Cook Islands - history and culture", :concept_type_id => THEME)
theme.children.create(:concept_name => "Fiji - history and culture", :concept_type_id => THEME)
theme.children.create(:concept_name => "Niue - history and culture", :concept_type_id => THEME)
theme.children.create(:concept_name => "Tonga - history and culture", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Culture - other"])
theme.children.create(:concept_name => "African", :concept_type_id => THEME)
theme.children.create(:concept_name => "Australian", :concept_type_id => THEME)
theme.children.create(:concept_name => "Indonesian", :concept_type_id => THEME)
theme.children.create(:concept_name => "Chinese", :concept_type_id => THEME)
theme.children.create(:concept_name => "Japanese", :concept_type_id => THEME)
theme.children.create(:concept_name => "Asian - other", :concept_type_id => THEME)
theme.children.create(:concept_name => "Indian", :concept_type_id => THEME)
theme.children.create(:concept_name => "French", :concept_type_id => THEME)
theme.children.create(:concept_name => "British", :concept_type_id => THEME)
theme.children.create(:concept_name => "German", :concept_type_id => THEME)
theme.children.create(:concept_name => "French", :concept_type_id => THEME)
theme.children.create(:concept_name => "Italian", :concept_type_id => THEME)
theme.children.create(:concept_name => "Spanish", :concept_type_id => THEME)
theme.children.create(:concept_name => "Portuguese", :concept_type_id => THEME)
theme.children.create(:concept_name => "Greek", :concept_type_id => THEME)
theme.children.create(:concept_name => "Scandinavian", :concept_type_id => THEME)
theme.children.create(:concept_name => "Russian", :concept_type_id => THEME)
theme.children.create(:concept_name => "Baltic States", :concept_type_id => THEME)
theme.children.create(:concept_name => "Balkan States", :concept_type_id => THEME)
theme.children.create(:concept_name => "Eastern European - other", :concept_type_id => THEME)
theme.children.create(:concept_name => "Middle East", :concept_type_id => THEME)
theme.children.create(:concept_name => "Canadian", :concept_type_id => THEME)
theme.children.create(:concept_name => "American - USA", :concept_type_id => THEME)
theme.children.create(:concept_name => "Latin American", :concept_type_id => THEME)
theme.children.create(:concept_name => "Jewish", :concept_type_id => THEME)
theme.children.create(:concept_name => "Ancient civilisations", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"The Elements"])
theme.children.create(:concept_name => "The elements", :concept_type_id => THEME)
theme.children.create(:concept_name => "Fire", :concept_type_id => THEME)
theme.children.create(:concept_name => "Sea and water - other", :concept_type_id => THEME)
theme.children.create(:concept_name => "Sea and water - NZ", :concept_type_id => THEME)
theme.children.create(:concept_name => "Space", :concept_type_id => THEME)
theme.children.create(:concept_name => "Air and Sky", :concept_type_id => THEME)
theme.children.create(:concept_name => "Weather", :concept_type_id => THEME)
theme.children.create(:concept_name => "Seasons", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Religion / Spirituality"])
theme.children.create(:concept_name => "Wedding", :concept_type_id => THEME)
theme.children.create(:concept_name => "Easter", :concept_type_id => THEME)
theme.children.create(:concept_name => "Bible", :concept_type_id => THEME)
theme.children.create(:concept_name => "Religious", :concept_type_id => THEME)
theme.children.create(:concept_name => "Spiritual", :concept_type_id => THEME)
theme.children.create(:concept_name => "Christmas", :concept_type_id => THEME)
theme.children.create(:concept_name => "Heaven and hell", :concept_type_id => THEME)
theme.children.create(:concept_name => "Birth", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Time"])
theme.children.create(:concept_name => "Time", :concept_type_id => THEME)
theme.children.create(:concept_name => "Seasons", :concept_type_id => THEME)
theme.children.create(:concept_name => "Historical Event", :concept_type_id => THEME)
theme.children.create(:concept_name => "Anniversary", :concept_type_id => THEME)
theme.children.create(:concept_name => "Night", :concept_type_id => THEME)
theme.children.create(:concept_name => "Day", :concept_type_id => THEME)
theme.children.create(:concept_name => "Travel", :concept_type_id => THEME)
theme.children.create(:concept_name => "Space", :concept_type_id => THEME)
theme.children.create(:concept_name => "Sleep", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Age"])
theme.children.create(:concept_name => "Age", :concept_type_id => THEME)
theme.children.create(:concept_name => "Birth", :concept_type_id => THEME)
theme.children.create(:concept_name => "Children/youth", :concept_type_id => THEME)
theme.children.create(:concept_name => "Life", :concept_type_id => THEME)
theme.children.create(:concept_name => "Death", :concept_type_id => THEME)
theme.children.create(:concept_name => "Sleep", :concept_type_id => THEME)
theme.children.create(:concept_name => "Old Age", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Humanity"])
theme.children.create(:concept_name => "Humanity", :concept_type_id => THEME)
theme.children.create(:concept_name => "Women", :concept_type_id => THEME)
theme.children.create(:concept_name => "Men", :concept_type_id => THEME)
theme.children.create(:concept_name => "Relationships", :concept_type_id => THEME)
theme.children.create(:concept_name => "Sexuality", :concept_type_id => THEME)
theme.children.create(:concept_name => "Change", :concept_type_id => THEME)
theme.children.create(:concept_name => "Mental wellbeing", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Celebration"])
theme.children.create(:concept_name => "Celebration", :concept_type_id => THEME)
theme.children.create(:concept_name => "Historical Event", :concept_type_id => THEME)
theme.children.create(:concept_name => "Anniversary", :concept_type_id => THEME)
theme.children.create(:concept_name => "Wedding", :concept_type_id => THEME)
theme.children.create(:concept_name => "Christmas", :concept_type_id => THEME)
theme.children.create(:concept_name => "Ceremony", :concept_type_id => THEME)
theme.children.create(:concept_name => "Play / Games", :concept_type_id => THEME)
theme.children.create(:concept_name => "Commemoration", :concept_type_id => THEME)
theme.children.create(:concept_name => "Food", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Love"])
theme.children.create(:concept_name => "Love", :concept_type_id => THEME)
theme.children.create(:concept_name => "Wedding", :concept_type_id => THEME)
theme.children.create(:concept_name => "Peace", :concept_type_id => THEME)
theme.children.create(:concept_name => "Good and Evil", :concept_type_id => THEME)
theme.children.create(:concept_name => "Beauty", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Mythology"])
theme.children.create(:concept_name => "Purakau - legends", :concept_type_id => THEME)
theme.children.create(:concept_name => "Myth", :concept_type_id => THEME)
theme.children.create(:concept_name => "Good and Evil", :concept_type_id => THEME)
theme.children.create(:concept_name => "Heaven and hell", :concept_type_id => THEME)
theme.children.create(:concept_name => "Play / Games", :concept_type_id => THEME)
theme.children.create(:concept_name => "Fairytale / folktale", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Language and Literature"])
theme.children.create(:concept_name => "Language and Literature", :concept_type_id => THEME)
theme.children.create(:concept_name => "Shakespeare", :concept_type_id => THEME)
theme.children.create(:concept_name => "Fairytale / folktale", :concept_type_id => THEME)
theme.children.create(:concept_name => "Art and literature - NZ", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Performing / Visual Arts"])
theme.children.create(:concept_name => "Music", :concept_type_id => THEME)
theme.children.create(:concept_name => "Dance", :concept_type_id => THEME)
theme.children.create(:concept_name => "Theatre", :concept_type_id => THEME)
theme.children.create(:concept_name => "Shakespeare", :concept_type_id => THEME)
theme.children.create(:concept_name => "Greek theatre", :concept_type_id => THEME)
theme.children.create(:concept_name => "Sculpture/ painting", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Politics"])
theme.children.create(:concept_name => "Politics", :concept_type_id => THEME)
theme.children.create(:concept_name => "Peace", :concept_type_id => THEME)
theme.children.create(:concept_name => "War", :concept_type_id => THEME)
theme.children.create(:concept_name => "Conservation", :concept_type_id => THEME)
theme.children.create(:concept_name => "Race Relations", :concept_type_id => THEME)
theme.children.create(:concept_name => "Kaupapa - protest", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"History"])
theme.children.create(:concept_name => "Politics", :concept_type_id => THEME)
theme.children.create(:concept_name => "War", :concept_type_id => THEME)
theme.children.create(:concept_name => "Historical Event", :concept_type_id => THEME)
theme.children.create(:concept_name => "Anniversary", :concept_type_id => THEME)
theme.children.create(:concept_name => "Ancient civilisations", :concept_type_id => THEME)
theme.children.create(:concept_name => "History - NZ", :concept_type_id => THEME)
theme.children.create(:concept_name => "Commemoration", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Travel / Migration"])
theme.children.create(:concept_name => "Travel", :concept_type_id => THEME)
theme.children.create(:concept_name => "Space", :concept_type_id => THEME)
theme.children.create(:concept_name => "Migration", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"Maths and Science"])
theme.children.create(:concept_name => "Mathematics", :concept_type_id => THEME)
theme.children.create(:concept_name => "Science", :concept_type_id => THEME)
theme.children.create(:concept_name => "Space", :concept_type_id => THEME)
theme.children.create(:concept_name => "Conservation", :concept_type_id => THEME)

theme = Concept.find(:first, :conditions => ["concept_type_id = ? and concept_name = ?", THEME,"No theme"])
theme.children.create(:concept_name => "[For works where the composer wants to make it clear that it is entirely abstract]", :concept_type_id => THEME)

