class ContributorRelationship < ActiveRecord::Base
set_primary_key "contributor_relationship_id"
set_sequence_name "contributor_relationships_contributor_relationship_id_seq"
belongs_to :contributor
belongs_to :relationship
belongs_to :relationship_type
end
